export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const FAVOURITE_PRODUCT = 'FAVOURITE_PRODUCT';
export const UNFAVOURITE_PRODUCT = 'UNFAVOURITE_PRODUCT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
